### ISSUE TITLE
Use of private field

### ISSUE THREAD

**Issue by ghost** [sewenew/redis-protobuf#11]
So I'm trying super hard to figure out how to use protobuf's reflection API for maps, and it's incredibly frustrating. Seems like you figured it out, and as I was skimming through your code, I came across this line:
https://github.com/sewenew/redis-protobuf/blob/master/src/sw/redis-protobuf/field_ref.h#L407

```
auto *map_base = reflection->MutableRaw<::google::protobuf::internal::MapFieldBase>(msg, field_desc);
```

Afaik, `MutableRaw` is a private member of gp::internall::GeneratedMessageReflection. How does your code compile?

**Comment by sewenew** [comment]
Yes, it's private. So in order to use map field reflection, I modified the code to make these interfaces public. Check [this](https://github.com/sewenew/redis-protobuf#install-protobuf) for detail.
