### ISSUE TITLE
redis proto directory

### ISSUE THREAD

**Issue by rushilV** [sewenew/redis-protobuf#12]
Environment : Linux
Hi am trying to run redis-protobuf through docker the problem here is in my local system i don't have any redis directory in /usr/lib also i need to place my own protobuf files, according to your Readme we need to place the proto files in /urs/lib/redis/proto directory.
Question here is do i manually need to create the redis directory in /usr/lib or do i need to follow any particular steps. Also from where the docker is reading the protofiles.

**Comment by sewenew** [comment]
If you're pulling the image from *hub.docker.com*, i.e. `docker run -p 6379:6379 sewenew/redis-protobuf:latest`, there should be a */usr/lib* directory.

Instead, if you're creating your own docker image, you don't need to put config files and proto files in the */usr/lib* directory. In fact, you can put these files in any directory, and follow the [direction](https://github.com/sewenew/redis-protobuf#load-redis-protobuf) to start Redis:

1. Prepare your *redis.conf* file, and ensure that you set the `loadmodule` directive: `loadmodule /path/to/libredis-protobuf.so --dir /path/to/your/proto/file/directory`
2. Start redis-server with *redis.conf* file: `redis-server /path/to/redis.conf`

If Redis successfully loads the module, you can see the following message: 

```
Module 'PB' loaded from /path/to/libredis-protobuf.so
```

If you still have any problem with it, feel free to let me know. If you like the module, also feel free to star it :)

Regards
