### ISSUE TITLE
document big O for each command

### ISSUE THREAD

**Issue by databasedav** [sewenew/redis-protobuf#19]
I was wondering what the runtime of `PB.APPEND` was and thought I would just raise this more general request. Thanks!

**Comment by sewenew** [comment]
Hi @databasedav 

The amortized time complexity of `PB.APPEND` command is O(1).

You suggestion is a good idea. I'll add document for these command.

Thanks a lot!

Regards

**Comment by sewenew** [comment]
Hi @databasedav 

The document has been updated to add time complexity info for these commands. Thanks again for your suggestion!

Regards
