### ISSUE TITLE
PB.TYPE maybe has a bug

### ISSUE THREAD

**Issue by wkliuwsk** [sewenew/redis-protobuf#22]
When the command is executed：

127.0.0.1:6379> PB.SCHEMA Msg3
"message Msg3 {\n  int32 i = 1;\n  SubMsg3 sub = 2;\n  repeated int32 arr = 3;\n}\n"
127.0.0.1:6379> PB.SCHEMA Msg2
"message Msg2 {\n  optional int32 i = 1;\n  optional SubMsg2 sub = 2;\n  repeated int32 arr = 3;\n}\n"
127.0.0.1:6379> PB.TYPE Msg2
(nil)
127.0.0.1:6379> PB.TYPE Msg3
(nil)
127.0.0.1:6379> PB.TYPE key Msg3
(error) ERR wrong number of arguments for 'PB.TYPE' command
127.0.0.1:6379> PB.TYPE key
(nil)
127.0.0.1:6379>

**Comment by sewenew** [comment]
@wkliuwsk I cannot reproduce the problem.

The `PB.TYPE` has the following syntax: `PB.TYPE key`. However, it seems that your `key` doesn't exist. You should set the key before calling `PB.TYPE`.

Try the following commands:

```
PB.SET key Msg3 '{"i" : 1}'

PB.TYPE key
```

Regards
