### ISSUE TITLE
Naive question: how host rpc in redis

### ISSUE THREAD

**Issue by EdmundsEcho** [sewenew/redis-protobuf#26]
An rpc specifies two messages. It's a naive question because it's likely obvious.  

Can I use this module to represent the rpc when the input message meets the criteria as a key (unique) and the return value another message. 

I want both values to be hosted as a proto buffer. 

Doable?

**Comment by sewenew** [comment]
redis-protobuf has nothing to do with rpc, instead, it's a protobuf store.

If I understand correctly, what you need is to write a Redis Module, which handles the rpc logic with protobuf as the request and reply message type.

Regards

**Comment by EdmundsEcho** [comment]
Yes.  You have it right.  So, I have an rpc:

```
service JobStatus {
    rpc RequestStatus (Ticket) returns (ResponseStatus) {}
}
message Ticket {
    NamespaceEnum namespace_enum = 1;
    ProjectId project_id = 1;
    JobTypeEnum job_type = 2;
    uint32 job_id = 3;
}
message ResponseStatus {
    ProjectId project_id = 1;
    JobTypeEnum job_type = 2;
    uint32 job_id = 3;
    StatusEnum status = 4;
}
```

The module would implement the server "end" of the rpc.  The module would extract and assemble the information from the `Ticket` required to lookup the key in Redis.  The module would also build the ResponseStatus from the key + value retrieved from Redis.

Otherwise, I would use something like Rust to implement the service. I would use a rust-redis client to make the calls to redis.  In this case, I would still want to store and retrieve the information as `Messages`.  

```
message RedisKey {
   NamespaceEnum namespace_enum = 1;
   ProjectId project_id = 2;
   JobTypeEnum job_type = 3;
   uint32 job_id = 4;
}
message Status {
   StatusEnum status = 1,
}
```

What do you think?

**Comment by sewenew** [comment]
> The module would implement the server "end" of the rpc. The module would extract and assemble the information from the Ticket required to lookup the key in Redis. The module would also build the ResponseStatus from the key + value retrieved from Redis.

Yes, that's exactly what the module should do.

Also your client code needs to serialize protobuf message to string before sending it to Redis, and parse the response from bytes to protobuf message, since Redis' protocol has no idea on protobuf.

Regards
