### ISSUE TITLE
Not working with Redis 6.x 

### ISSUE THREAD

**Issue by AnujaK** [sewenew/redis-protobuf#27]
This module is not getting loaded in either Redis 6.x or Redis Stack. Getting error:
`Can't load module from /home/anuja/redis-protobuf/compile/libredis-protobuf: server aborting`

Does it work with very specific redis version(s) @sewenew ?

**Comment by sewenew** [comment]
It should work with Redis 6.X. I tested it with Redis 5.0.9, Redis 6.0.1 and Redis 7.0.0. redis-protobuf works on these version.

What's error message does it report? Also you should specify the full name of the dynamic library, including the file extension:

```
loadmodule /path/to/libredis-protobuf.so --dir /path/to/proto/dir
```

Regards

**Comment by AnujaK** [comment]
It is running with Docker. Did not test the dockerized version with Redis Stack (7.0) as I had already downgraded the redis version to 6.2 in an attempt to make the loadmodule work. The only error is 

> Can't load module from /home/anuja/redis-protobuf/compile/libredis-protobuf: server aborting

**Comment by sewenew** [comment]
You can try the [Dockerfile](https://github.com/sewenew/redis-protobuf/blob/master/docker/Dockerfile) in the project, which tests with the latest Redis. It should work.

Regards

**Comment by sewenew** [comment]
Since there's no update. I'll close this issue.

Regards
